name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go 

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Build Project
      run: make build

    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GH_ACTIONS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GH_ACTIONS_AWS_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 buckets for bins / cf stack
      run: make s3
      
    - name: Cloudformation package
      if: always()
      run: make package

    - name: Cloudformation Deploy
      run: make deploy
